auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Allan's Blog
url: http://blog.allanhost.com
feed: /atom.xml
author_info: <a href="http://blog.allanhost.com/">AllanChan</a>
